apiVersion: v1
kind: Secret
metadata:
  name: testcluster-pull-secret
  namespace: testcluster
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "cloud.openshift.com": {
        },
        "quay.io": {
        },
        "registry.connect.redhat.com": {
        },
        "registry.redhat.io": {
        }
      }
    }
type: kubernetes.io/dockerconfigjson
